add naming functionality
hpi-schul-cloud/infra-tools pull request #22
Opened 2022-05-16 08:14 UTC by aimee-889

# Description
add naming functionality for uploading s3 secrets

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/OPS-3313

## Changes
n/a

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>
n/a

## Deployment
n/a

## New Repos, NPM pakages or vendor scripts
n/a

## Screenshots of UI changes
n/a

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-05-20 14:00 UTC, BlexToGo requested changes
Found some potential simplifications

2022-05-23 06:53 UTC, aimee-889 commented on onepwd/src/onepwd/__init__.py
> +    if index < 20:
rewrote this to use the actual number of sections instead to break the while loop

2022-05-23 06:57 UTC, aimee-889 commented on onepwd/plugins/action/update_s3_values_of_item.py
> +        #         pass
i would like to leave it, but also would be fine with deleting it

2022-05-23 12:38 UTC, BlexToGo approved these changes

2022-05-24 16:09 UTC, dimapin approved these changes

2022-06-16 08:10 UTC, merged